spring:
  banner:
    location: logo-app
    charset: UTF-8
  profiles:
    active: default

  h2:
    console:
      path: /my-new-h2-console
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/words;DATABASE_TO_UPPER=false
    username: mazo12
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl